LangData:={
en: {
Name: "English",
Flag: "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAHYcAAB2HAGnwnjqAAAE7mlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgOS4xLWMwMDEgNzkuMTQ2Mjg5OSwgMjAyMy8wNi8yNS0yMDowMTo1NSAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3AvMS4wLyIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0RXZ0PSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VFdmVudCMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIDI1LjMgKFdpbmRvd3MpIiB4bXA6Q3JlYXRlRGF0ZT0iMjAyNC0wMS0yNVQwOToyMToyMiswNzowMCIgeG1wOk1vZGlmeURhdGU9IjIwMjQtMDEtMjVUMTA6NTg6MjkrMDc6MDAiIHhtcDpNZXRhZGF0YURhdGU9IjIwMjQtMDEtMjVUMTA6NTg6MjkrMDc6MDAiIGRjOmZvcm1hdD0iaW1hZ2UvcG5nIiBwaG90b3Nob3A6Q29sb3JNb2RlPSIzIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOmU3YWFmNDRiLTcyNGUtMGI0Yy04MDExLTE1NDZlMzgyNDI2ZSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDplN2FhZjQ0Yi03MjRlLTBiNGMtODAxMS0xNTQ2ZTM4MjQyNmUiIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDplN2FhZjQ0Yi03MjRlLTBiNGMtODAxMS0xNTQ2ZTM4MjQyNmUiPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJjcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOmU3YWFmNDRiLTcyNGUtMGI0Yy04MDExLTE1NDZlMzgyNDI2ZSIgc3RFdnQ6d2hlbj0iMjAyNC0wMS0yNVQwOToyMToyMiswNzowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIDI1LjMgKFdpbmRvd3MpIi8+IDwvcmRmOlNlcT4gPC94bXBNTTpIaXN0b3J5PiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/Ph33cm0AAAO8SURBVDjLhZRdiJRVHMZ/553ZxZ3VtFK60SAW1NmPmXX3YkOjLWzWNhW9qQuRSiGL1CCiIsOLIkq0qNw1hEW8SUwv/IDSdCmIUsjPVCo1pWz2Q9Kd3XZmnY/3PefpYnZnxr58OA/8zzkPz/mfl+c9SGKCu49ehllboOFDGlbvQVKHWudtFPQIetTavFHSosZn90LTVnhwP/ve3408EEWGqYAmVo2Z72FeA5YgFyoLALDG8DnGbEYcl7gNXuUkmwvgxkg3k8wxD28ZEJrwUdkxZIy3jCp7jNTN7mzN1H83FLAkMfvw4udb13JhkEy2UNooGY53M5bJwpURln7w5NpFk28cwlVec/Fj6KE27Pr13RrHho++sdM6d7icldTSLAuyILU0K2elaWuOuDd7//DV9bYEsqtWd2nLe+jjzXDuqRfof/HlJoGCe6dLZ09bSbrY/6cd9iUXj5UMXTyuVCBdPvVjoPa4FQSFPXudJA1IsXMS1G04Sdsnvx49+VtKbtEjzo9GXf7E91aSAkl+U5N8KHLePPmS1LlQwZy5Nnfzph9IOnU1pbZnPuutW7oDrJRI+06DknITzGRKtR+LlQ1jsdJ6tkI/mHdKS3JSImxamtsnG6gNHIHxIBwG5yAIwBiUTEJtbfGDJ5N48ThUVYG1RQ1wX8jDhAwYrz3snz03k/9DJAKh8Sjm83D+/D8kfjkpM8PiDqhMru6oJuw1x/o8CedEYMcDFQ4Xu/J9TDIJ/ngP1dWorq5oHAqNawLCOLyQB57XR1ZKpApW10ZzSksa/RvHGhs1BkU2Npb3hoZK9TVJqWxOo3IJr2FpT2/Hql29A33DVAPu+nVr5sxxUzraMYAzpvSnOGvxgCmAu3TJmdmzVZN4WANX+uncPtjbsv6nXr4dERelWCBp6NNdLgeB5je4H747EyRvFZSJRjUKGgVlolElMzmd+WXAStLYqZN2ZOrdEujCitVNXz++ArTpLfKb3mFo5cougbT5Db164GoQefqAG8kHutUQ1QhoBIp1IVDk0S73yrtflMI//Nya7ly8ATu/FRxl9m/deiix65qoeV0zl2yXLyldP1cpUAqUrp8rX9Ks5T2Cl7Rw1U71DacPu4o31TOAAYyBfekZT/Ru2L+NByLURKooYHHOlQ91jgKWSdUG6qfz1c7T2/Z/+XOn+a/3sDabhhnT15H3FlgbHHQ465zKhnI4OWudDmJZwD13rauNVN2ew8qJMYARWO+4LMsNXodFbQ7uB7BOv1fBCYx3BExxmNuD/RcidbCGL60y7QAAAABJRU5ErkJggg==",
AUOptions: {Name: "AUOptions", Desc: "Set Notify before download Windows Updates"},
AutoEndTasks: {Name: "Auto End Tasks", Desc: "Close frozen processes to avoid system crash"},
BtnClearStartMenu: {Name: "Clear StartMenu"},
Text_DeselectAll: "Deselect All",
BtnHostEdit: {Name: "Host Edit"},
BtnRestartExplorer: {Name: "Restart Explorer"},
Text_SelectAll: "Select All",
BtnStartupManager: {Name: "Startup Manager"},
BtnSys_Close: {Desc: "Close"},
BtnSys_Language: {Desc: "Language"},
BtnSys_LoadOptimizeConfig: {Desc: "Load optimization configurations file"},
BtnSys_Minimize: {Desc: "Minimize"},
BtnSys_SaveImage: {Desc: "Self-Capture and Save to Image"},
BtnSys_SaveOptimizeConfigAll: {Desc: "Save all optimization configurations to file"},
BtnSys_SaveOptimizeConfigTab: {Desc: "Save this tab only optimization configuration to file"},
BtnSys_Setting: {Desc: "Setting"},
BtnSys_Theme: {Desc: "Theme"},
ClassicContextMenu: {Name: "Classic Context Menu"},
DiagnosticDataOff: {Name: "Diagnostic Data Off"},
DisableAdsOnLockScreen: {Name: "Disable Ads On Lock Screen"},
DisableAeDebug: {Name: "Disable AeDebug", Desc: "Disable the debugger to speed up error processing"},
DisableAnimationEffectMaxMin: {Name: "Disable Animation Effect Max Min", Desc: "Close animation effect when maximizing or minimizing a window to speed up the window response"},
DisableAppendCompletion: {Name: "Disable Append Completion", Desc: "Disable inline Auto-Complete (Append completion or Auto-fill)"},
DisableAutoDefragIde: {Name: "Disable Auto Defrag Ide", Desc: "Disable auto defrag when ide to increase working life of SSD"},
DisableAutoInstallationApps: {Name: "Disable Auto Installation Apps"},
DisableAutoplay: {Name: "Disable Autoplay", Desc: "Disable the “Autoplay” feature on drives to avoid virus infection"},
DisableAutoSuggest: {Name: "Disable Auto-Suggest", Desc: "Disable Auto-Suggest (Auto-complete drop-down)"},
DisableAutoWindowsUpdates: {Name: "Disable Auto Windows Updates", Desc: "Disable Automatic Updates"},
DisableBackgroundApps: {Name: "Disable Background Apps"},
DisableBingSearchStartMenu: {Name: "Disable BingSearch Start Menu"},
DisableBootOptimize: {Name: "Disable Boot Optimize", Desc: "Disable defrag system drive on boot to increase working life of SSD"},
DisableCortana: {Name: "Disable Cortana"},
DisableCortanaWindowsSearch: {Name: "Disable Cortana Windows Search", Desc: "Stops Cortana from being used as part of your Windows Search Function"},
DisableCrashAutoReboot: {Name: "Disable Crash Auto Reboot", Desc: "Disable automatical reboot when system encounters blue screen of death"},
DisableDiagTrack: {Name: "Disable DiagTrack"},
DisabledVBSCodeIntegrity: {Name: "Disabled VBS Code Integrity", Desc: "Disable virtualization-based protection of code integrity"},
DisableErrorReporting: {Name: "Disable Error Reporting", Desc: "Disable screen error reporting to improve system performance"},
DisableFrequentFolders: {Name: "Disable FrequentFolders"},
DisableGameBar: {Name: "Disable Game Bar & Game DVR", Desc: "The Game DVR feature allows you to record your gameplay in the background.`nIt is located on the Game Bar – which offers buttons to record gameplay & take screenshots using the Game DVR feature.`nBut it can slow your gaming performance by recording video in the background."},
DisableGoogleUpdateTask: {Name: "Disable GoogleUpdateTask"},
DisableHibernate: {Name: "Disable Hibernate"},
DisableHybridSleep: {Name: "Disable Hybrid Sleep"},
DisableLockScreen: {Name: "Disable Lock Screen"},
DisableLowDiskSpaceChecks: {Name: "Disable Low Disk Space Checks", Desc: "Optimize disk I/O subsystem to improve system performance"},
Disablememorypagination: {Name: "Disable memory pagination", Desc: "Disable memory pagination and reduce disk I/O to improve application performance.`n(Option may be ignored if physical memory is <1 GB)"},
DisableMenuShowDelay: {Name: "Disable Menu Show Delay", Desc: "Optimized response speed of system display"},
DisableMicrosoftEdgeUpdateTask: {Name: "Disable MicrosoftEdgeUpdateTask"},
DisableOfferSuggestions: {Name: "Disable Offer Suggestions"},
DisablePersonalizedAdsStoreApps: {Name: "Disable PersonalizedAds StoreApps"},
DisablePrefetchParameters: {Name: "Disable Prefetch Parameters", Desc: "Disable prefetch parameters to increase SSD working life"},
DisablePrintSpooler: {Name: "Disable Print Spooler"},
DisableRecentFiles: {Name: "Disable RecentFiles"},
DisableRemoteRegAccess: {Name: "Disable Remote Reg Access", Desc: "Disable registry modification from a remote computer"},
DisableScheduledDefrag: {Name: "Disable Scheduled Defrag"},
DisableSettingsAppSuggestions: {Name: "Disable Settings App Suggestions"},
DisableShortcutText: {Name: "Disable Shortcut Text"},
DisableSleep: {Name: "Disable Sleep"},
DisableSyncProviderNotifications: {Name: "Disable Sync Provider Notifications"},
DisableSystemRestore: {Name: "Disable System Restore"},
DisableTailoredExperiences: {Name: "Disable Tailored Experiences"},
DisableTipsAndSuggestions: {Name: "Disable Tips And Suggestions"},
DisableTurnOffDisplay: {Name: "Disable Turn Off Display"},
DisableVisualStudioTelemetry: {Name: "Disable VisualStudio Telemetry"},
DisableWCE: {Name: "Disable WCE Improvement", Desc: "Disable Windows Customer Experience Improvement`n`n- Proxy: This task collects and uploads autochk SQM data if opted-in to the Microsoft Customer Experience Improvement Program.`n- Microsoft Compatibility Appraiser: Collects program telemetry information if opted-in to the Microsoft Customer Experience Improvement Program."},
DisableWebSearch: {Name: "Disable Web Search"},
DisableWebSearchStartMenu: {Name: "Disable WebSearch Start Menu", Desc: "Disables Web Search in Start Menu"},
DisableWindowsFeedback: {Name: "Disable Windows Feedback"},
DisableWindowsSearch: {Name: "Disable Windows Search"},
EnableDarkMode: {Name: "Enable Dark Mode"},
HostEdit_BtnImportFromFile: {Name: "Import From Files"},
HostEdit_BtnImportFromLink: {Name: "Import From Link"},
HostEdit_BtnInsertLink: {Desc: "Insert link for Import to host"},
HostEdit_BtnReload: {Name: "Reload host file"},
HostEdit_BtnResetDefault: {Name: "Reset Default"},
HostEdit_BtnSave: {Name: "Save"},
HostEdit_BtnSaveAs: {Name: "Save As"},
IncreaseIconCache: {Name: "Increase Icon Cache", Desc: "Increase system icon cache and speed up desktop display"},
IoPageLockLimit: {Name: "Io Page Lock Limit", Desc: "Optimize the defauit settings of memory to improve system performance"},
LinkResolveIgnoreLinkInfo: {Name: "Link Resolve Ignore LinkInfo", Desc: "Do not track Shell shortcuts during roaming"},
MouseHoverTime: {Name: "Mouse Hover Time", Desc: "Speed up display speed of Taskbar Window Previews"},
NoInternetOpenWith: {Name: "No Internet OpenWith", Desc: "Turn off Internet File Association service"},
NoResolveSearch: {Name: "No Resolve Search", Desc: "Do not use the search-based method when resolving shell shortcuts"},
NumLockonStartup: {Name: "Num Lock on Startup"},
OpenFileExplorerThisPC: {Name: "Open File Explorer ThisPC"},
OptimizeNetworkTransfer: {Name: "Optimize Network Transfer", Desc: "Optimize network settings to improve transfer performance"},
Optimizeprocessorperformance: {Name: "Optimize processor performance", Desc: "Optimize processor performance to make applications, games, etc. run more smoothly."},
OptimizeRefreshPolicy: {Name: "Optimize Refresh Policy", Desc: "Optimize disk I/O subsystem to improve system performance"},
Optional: {Name: "Optional"},
Privacy: {Name: "Privacy"},
ShowExtensions: {Name: "Show Extensions"},
ShowHidden: {Name: "Show Hidden"},
ShowHiddenSystem: {Name: "Show Hidden System"},
ShowThisPC: {Name: "Show ThisPC"},
ShutdownAcceleration: {Name: "Shutdown Acceleration", Desc: "Reduce application idleness at shutdown to improve the shutdown process"},
SnippingPrintScreen: {Name: "Snipping PrintScreen"},
System: {Name: "System"},
UninstallOneDrive: {Name: "Uninstall OneDrive"},
UnpinChat: {Name: "Chat"},
UnpinCopilot: {Name: "Copilot"},
UnpinCortana: {Name: "Cortana"},
UnpinEdge: {Name: "Edge"},
UnpinFileExplorer: {Name: "File Explorer"},
UnpinMail: {Name: "Mail"},
UnpinNewsandInterests: {Name: "News and Interests"},
UnpinSearch: {Name: "Search"},
UnpinStore: {Name: "Store"},
UnpinTaskbar: {Name: "Unpin Taskbar"},
UnpinTaskView: {Name: "TaskView"},
UnpinWidgets: {Name: "Widgets"},
Text_WaitDlg: "Please wait...",
Text_ClearStartMenu_Done: "Clear StartMenu Done!",
DisableMSDefender: {Name: "Disable Microsoft Defender", Desc: "Enable/Disable Microsoft Defender with 1-click.`nIt will automatically restart the computer."},
Text_DisableMSDefender1: "Disabling Microsoft Defender requires restarting the computer.`nAre you sure you want to perform this?",
Text_DisableMSDefender0: "Enabling Microsoft Defender requires restarting the computer.`nAre you sure you want to perform this?",
Text_Enable: "Enable",
Text_Enabled: "Enabled",
Text_Disable: "Disable",
Text_Disabled: "Disabled",
Text_Properties: "Properties",
Text_Delete: "Delete",
Text_OpenTarget: "Target location",
Text_FindRegistry: "Find in Registry",
Text_SearchOnline: "Search online",
Text_Name: "Name",
Text_Status: "Status",
Text_CommandLine: "Command line",
Text_Target: "Target",
Text_Type: "Type",
Text_HR_Tools: "-------- Tools --------",
Text_HR_Optimize: "------- Optimize -------",
BtnSys_ReloadTab: {Desc: "Reload this tab"},
BtnPackageManager: {Name: "UWP Apps"},
Text_PublisherDisplayName: "Publisher",
Text_Architecture: "Architecture",
Text_Version: "Version",
Text_InstalledMode: "Installed Mode",
Text_NotInstalledMode: "Not Installed Mode",
Text_Install: "Install",
Text_Uninstall: "Uninstall",
Text_Details: "Details",
Text_OK: "OK",
Text_DisplayName: "Display name",
Text_FamilyName: "Family name",
Text_FullName: "Full name",
Text_SignatureKind: "Signature kind",
Text_InstalledPath: "Installed path",
Text_EffectivePath: "Effective path",
PackageManager_BtnDisable: {Desc: "Enable/Disable for all users"},
PackageManager_Mode: {Desc: "Installed Mode: Show list of installed packages.`nNot Installed Mode: Show list that is on your computer but not installed by the current user."},
PackageManager_DeprovisionPackage: {Name: "Deprovision Package", Desc: "Deprovisions an app Package so new users on the device will no longer have the app automatically installed."},
PackageManager_InstalledAllUsers: {Name: "All Users", Desc: "Show list of installed packages by all users."}
},
zh_cn: {
Name: "中文（简体）",
Translator: "Jvcon",
Flag: "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAHYcAAB2HAGnwnjqAAAE7mlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgOS4xLWMwMDEgNzkuMTQ2Mjg5OSwgMjAyMy8wNi8yNS0yMDowMTo1NSAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3AvMS4wLyIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0RXZ0PSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VFdmVudCMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIDI1LjMgKFdpbmRvd3MpIiB4bXA6Q3JlYXRlRGF0ZT0iMjAyNC0wMS0yNFQyMjoyOTowMiswNzowMCIgeG1wOk1vZGlmeURhdGU9IjIwMjQtMDEtMjVUMTA6NTg6NDgrMDc6MDAiIHhtcDpNZXRhZGF0YURhdGU9IjIwMjQtMDEtMjVUMTA6NTg6NDgrMDc6MDAiIGRjOmZvcm1hdD0iaW1hZ2UvcG5nIiBwaG90b3Nob3A6Q29sb3JNb2RlPSIzIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOmVkNWQ2MjVmLTc1MzEtMWE0Ny1iNWFjLTc4MDVmYjIyYjNlNSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDplZDVkNjI1Zi03NTMxLTFhNDctYjVhYy03ODA1ZmIyMmIzZTUiIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDplZDVkNjI1Zi03NTMxLTFhNDctYjVhYy03ODA1ZmIyMmIzZTUiPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJjcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOmVkNWQ2MjVmLTc1MzEtMWE0Ny1iNWFjLTc4MDVmYjIyYjNlNSIgc3RFdnQ6d2hlbj0iMjAyNC0wMS0yNFQyMjoyOTowMiswNzowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIDI1LjMgKFdpbmRvd3MpIi8+IDwvcmRmOlNlcT4gPC94bXBNTTpIaXN0b3J5PiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/Pl2SEAcAAAOYSURBVDjLhZTNb1VVFMV/+9xz73uvH7YVBYEGUAkRNKmRRIzEMFBLBxpw5syBI5SRJA79A0yYFUmc6H9gSBiAH4kkQqIThZDgxAAWSiGlrbSv771779nLwUOwReJK1mDv7LOyP87eJh5icctz1AMbMHURDkVrUvJ9wDYAxAz4z1ZzNqPCY07s9hi9fuWBRmQdTIIse12WfYr8HYwMIN2JWFOEMSVhp5XC56AL69+HNYac1AzTdZmf9yoekilTApVGc/Iexatt0kLMZByqs+J8isV0SL5GMGqoBSbwQG9g+Ezq2cHsiRJkqGvg4IsZI5/dor6Z0/nueaxwaAiJj7uNxs5hG51CBhjW3fYCmFgphr7oeH6EPwJj0zPUVwuWpzeSbaqwpojjJd4LpJkcrWaE0RqLImU5jU51cnBl4SPDCD1PrJbZRPWMjhQbutiI03p3icZrbVQa8dmSMJooL7eoLjcpXumw8cffibt6pIVISDW9VnakM5BPdJoQennOKq3jFmrGvrzG5quXECLubbN18VeGjs2Rlg2aCRuu8Q7UcxHvgqIjObjoFEPHe9bAZnfvfRvzb30uYk8knvz6Os0DywC0v3qKxU+2Yi0RxmoM8NVAulWQPV0RRhKqDRBYwLHJkJIfUIKwqaa61oDaSHdyBNR3ImkpJ4zVKBnCIINsa9kfihsChCEJww8Eg3FJ1HcDrfcWcYnZF3cz98Yu8olV4kttUifwT0zc02HjT1fI9nSo7/b9D+gaD0IIYNCp5yLzH2xHmSgvNbl7dBwbTJA59e3YL/deYOWbUdJ8hnLdz/Aho6MbCKwQ9WyEwrGGsFFQ16hv95ep9f4ClEbn9AjdY+NkWypsKKF//WuZ3QhyzglwFyqEcuEO7vTtINJfgYEP52keXsS7Rthcoux+HOD9zSc552xm+y6qvPG9LLwZJB6BgCis5agb0ErAmmvj3AyT/xDL3ls2u2UHHuLEamv4t8xrHgd1AhiEwYSSrRUMgWZ7+eWQ0sUQ7/UoltoXi/bKySoLyB3/D6pRo6ImVXroc6e0QN7zk41KF4sUMH9QmXF1fOeZsmgczFLif2FGskCj6p7dcXN+ytTPOvRvBAREs9OesqQTCXDp8UQkdxAnmr3OVNASxiLG4tp7qBDIaz8aqnq/y0+5lFy+XjB50qm8KvcXqT7qIVt7Dx9pvoElv4DZYYiTmPY52nZ/DH9i/BJdZ4O8X9o6/A0kGDN/Gi4umQAAAABJRU5ErkJggg==",
AUOptions: {Name: "AU选项", Desc: "在下载Windows更新前设置通知"},
AutoEndTasks: {Name: "自动结束任务", Desc: "关闭冻结的进程以避免系统崩溃"},
BtnClearStartMenu: {Name: "清除开始菜单"},
Text_DeselectAll: "取消全选",
BtnHostEdit: {Name: "主机编辑"},
BtnRestartExplorer: {Name: "重启资源管理器"},
Text_SelectAll: "全选",
BtnSys_Close: {Desc: "关闭"},
BtnSys_Language: {Desc: "语言"},
BtnSys_LoadOptimizeConfig: {Desc: "加载优化配置文件"},
BtnSys_Minimize: {Desc: "最小化"},
BtnSys_SaveImage: {Desc: "自我捕捉并保存为图像"},
BtnSys_SaveOptimizeConfigAll: {Desc: "将所有优化配置保存到文件"},
BtnSys_SaveOptimizeConfigTab: {Desc: "仅保存此标签的优化配置到文件"},
BtnSys_Setting: {Desc: "设置"},
BtnSys_Theme: {Desc: "主题"},
ClassicContextMenu: {Name: "经典上下文菜单"},
DiagnosticDataOff: {Name: "诊断数据关闭"},
DisableAdsOnLockScreen: {Name: "禁用锁屏广告"},
DisableAeDebug: {Name: "禁用AeDebug", Desc: "禁用调试器以加快错误处理"},
DisableAnimationEffectMaxMin: {Name: "禁用最大最小动画效果", Desc: "关闭窗口最大化或最小化时的动画效果以加快窗口响应速度"},
DisableAppendCompletion: {Name: "禁用追加完成", Desc: "禁用内联自动完成（追加完成或自动填充）"},
DisableAutoDefragIde: {Name: "禁用IDE自动碎片整理", Desc: "禁用IDE时的自动碎片整理以延长SSD的使用寿命"},
DisableAutoInstallationApps: {Name: "禁用自动安装应用"},
DisableAutoplay: {Name: "禁用自动播放", Desc: "禁用驱动器上的“自动播放”功能以避免病毒感染"},
DisableAutoSuggest: {Name: "禁用自动建议", Desc: "禁用自动建议（自动完成下拉）"},
DisableAutoWindowsUpdates: {Name: "禁用自动Windows更新", Desc: "禁用自动更新"},
DisableBackgroundApps: {Name: "禁用后台应用"},
DisableBingSearchStartMenu: {Name: "禁用Bing搜索开始菜单"},
DisableBootOptimize: {Name: "禁用启动优化", Desc: "禁用启动时对系统驱动器的碎片整理以延长SSD的使用寿命"},
DisableCortana: {Name: "禁用Cortana"},
DisableCortanaWindowsSearch: {Name: "禁用Cortana Windows搜索", Desc: "停止使用Cortana作为你的Windows搜索功能的一部分"},
DisableCrashAutoReboot: {Name: "禁用崩溃自动重启", Desc: "当系统遇到蓝屏死机时禁用自动重启"},
DisableDiagTrack: {Name: "禁用DiagTrack"},
DisabledVBSCodeIntegrity: {Name: "禁用VBS代码完整性", Desc: "禁用基于虚拟化的代码完整性保护"},
DisableErrorReporting: {Name: "禁用错误报告", Desc: "禁用屏幕错误报告以提高系统性能"},
DisableFrequentFolders: {Name: "禁用常用文件夹"},
DisableGameBar: {Name: "禁用游戏栏和游戏DVR", Desc: "游戏DVR功能允许你在后台记录你的游戏。它位于游戏栏上 - 提供了使用游戏DVR功能记录游戏和截图的按钮。但是，通过在后台录制视频，它可能会降低你的游戏性能。"},
DisableGoogleUpdateTask: {Name: "禁用Google更新任务"},
DisableHibernate: {Name: "禁用休眠"},
DisableHybridSleep: {Name: "禁用混合休眠"},
DisableLockScreen: {Name: "禁用锁屏"},
DisableLowDiskSpaceChecks: {Name: "禁用低磁盘空间检查", Desc: "优化磁盘I/O子系统以提高系统性能"},
Disablememorypagination: {Name: "禁用内存分页", Desc: "禁用内存分页并减少磁盘I/O以提高应用程序性能。`n(如果物理内存<1 GB，此选项可能会被忽略)"},
DisableMenuShowDelay: {Name: "禁用菜单显示延迟", Desc: "优化系统显示的响应速度"},
DisableMicrosoftEdgeUpdateTask: {Name: "禁用Microsoft Edge更新任务"},
DisableOfferSuggestions: {Name: "禁用提供建议"},
DisablePersonalizedAdsStoreApps: {Name: "禁用个性化广告商店应用"},
DisablePrefetchParameters: {Name: "禁用预取参数", Desc: "禁用预取参数以延长SSD的使用寿命"},
DisablePrintSpooler: {Name: "禁用打印服务"},
DisableRecentFiles: {Name: "禁用最近的文件"},
DisableRemoteRegAccess: {Name: "禁用远程注册访问", Desc: "禁止从远程计算机修改注册表"},
DisableScheduledDefrag: {Name: "禁用计划碎片整理"},
DisableSettingsAppSuggestions: {Name: "禁用设置应用建议"},
DisableShortcutText: {Name: "禁用快捷方式文本"},
DisableSleep: {Name: "禁用睡眠"},
DisableSyncProviderNotifications: {Name: "禁用同步提供商通知"},
DisableSystemRestore: {Name: "禁用系统还原"},
DisableTailoredExperiences: {Name: "禁用定制体验"},
DisableTipsAndSuggestions: {Name: "禁用提示和建议"},
DisableTurnOffDisplay: {Name: "禁用关闭显示"},
DisableVisualStudioTelemetry: {Name: "禁用VisualStudio遥测"},
DisableWCE: {Name: "禁用WCE改进", Desc: "禁用Windows客户体验改进`n`n- 代理：此任务收集并上传autochk SQM数据，如果选择加入Microsoft客户体验改进计划。`n- Microsoft兼容性评估器：如果选择加入Microsoft客户体验改进计划，将收集程序遥测信息。"},
DisableWebSearch: {Name: "禁用网络搜索"},
DisableWebSearchStartMenu: {Name: "禁用网络搜索开始菜单", Desc: "禁用开始菜单中的网络搜索"},
DisableWindowsFeedback: {Name: "禁用Windows反馈"},
DisableWindowsSearch: {Name: "禁用Windows搜索"},
EnableDarkMode: {Name: "启用暗黑模式"},
HostEdit_BtnImportFromFile: {Name: "从文件导入"},
HostEdit_BtnImportFromLink: {Name: "从链接导入"},
HostEdit_BtnInsertLink: {Desc: "插入链接以导入到主机"},
HostEdit_BtnReload: {Name: "重新加载主机文件"},
HostEdit_BtnResetDefault: {Name: "重置默认"},
HostEdit_BtnSave: {Name: "保存"},
HostEdit_BtnSaveAs: {Name: "另存为"},
IncreaseIconCache: {Name: "增加图标缓存", Desc: "增加系统图标缓存并加快桌面显示速度"},
IoPageLockLimit: {Name: "I/O页面锁定限制", Desc: "优化内存的默认设置以提高系统性能"},
LinkResolveIgnoreLinkInfo: {Name: "链接解析忽略链接信息", Desc: "在漫游时不跟踪Shell快捷方式"},
MouseHoverTime: {Name: "鼠标悬停时间", Desc: "加快任务栏窗口预览的显示速度"},
NoInternetOpenWith: {Name: "无互联网打开方式", Desc: "关闭互联网文件关联服务"},
NoResolveSearch: {Name: "无解析搜索", Desc: "在解析shell快捷方式时不使用基于搜索的方法"},
NumLockonStartup: {Name: "启动时数字锁定"},
OpenFileExplorerThisPC: {Name: "打开文件资源管理器ThisPC"},
OptimizeNetworkTransfer: {Name: "优化网络传输", Desc: "优化网络设置以提高传输性能"},
Optimizeprocessorperformance: {Name: "优化处理器性能", Desc: "优化处理器性能使应用程序、游戏等运行更加流畅。"},
OptimizeRefreshPolicy: {Name: "优化刷新策略", Desc: "优化磁盘I/O子系统以提高系统性能"},
Optional: {Name: "可选"},
Privacy: {Name: "隐私"},
ShowExtensions: {Name: "显示扩展名"},
ShowHidden: {Name: "显示隐藏文件"},
ShowHiddenSystem: {Name: "显示隐藏的系统文件"},
ShowThisPC: {Name: "显示此电脑"},
ShutdownAcceleration: {Name: "关机加速", Desc: "减少关机时的应用程序空闲以改善关机过程"},
SnippingPrintScreen: {Name: "截图打印屏幕"},
System: {Name: "系统"},
UninstallOneDrive: {Name: "卸载OneDrive"},
UnpinChat: {Name: "取消固定聊天"},
UnpinCopilot: {Name: "取消固定Copilot"},
UnpinCortana: {Name: "取消固定Cortana"},
UnpinEdge: {Name: "取消固定Edge"},
UnpinFileExplorer: {Name: "取消固定文件资源管理器"},
UnpinMail: {Name: "取消固定邮件"},
UnpinNewsandInterests: {Name: "取消固定新闻和兴趣"},
UnpinSearch: {Name: "取消固定搜索"},
UnpinStore: {Name: "取消固定商店"},
UnpinTaskbar: {Name: "取消固定任务栏"},
UnpinTaskView: {Name: "取消固定任务视图"},
UnpinWidgets: {Name: "取消固定小部件"}
}
}