LangData:= {
en: {
Name: "English",
Flag: "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAHYcAAB2HAGnwnjqAAAE7mlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgOS4xLWMwMDEgNzkuMTQ2Mjg5OSwgMjAyMy8wNi8yNS0yMDowMTo1NSAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3AvMS4wLyIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0RXZ0PSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VFdmVudCMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIDI1LjMgKFdpbmRvd3MpIiB4bXA6Q3JlYXRlRGF0ZT0iMjAyNC0wMS0yNVQwOToyMToyMiswNzowMCIgeG1wOk1vZGlmeURhdGU9IjIwMjQtMDEtMjVUMTA6NTg6MjkrMDc6MDAiIHhtcDpNZXRhZGF0YURhdGU9IjIwMjQtMDEtMjVUMTA6NTg6MjkrMDc6MDAiIGRjOmZvcm1hdD0iaW1hZ2UvcG5nIiBwaG90b3Nob3A6Q29sb3JNb2RlPSIzIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOmU3YWFmNDRiLTcyNGUtMGI0Yy04MDExLTE1NDZlMzgyNDI2ZSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDplN2FhZjQ0Yi03MjRlLTBiNGMtODAxMS0xNTQ2ZTM4MjQyNmUiIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDplN2FhZjQ0Yi03MjRlLTBiNGMtODAxMS0xNTQ2ZTM4MjQyNmUiPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJjcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOmU3YWFmNDRiLTcyNGUtMGI0Yy04MDExLTE1NDZlMzgyNDI2ZSIgc3RFdnQ6d2hlbj0iMjAyNC0wMS0yNVQwOToyMToyMiswNzowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIDI1LjMgKFdpbmRvd3MpIi8+IDwvcmRmOlNlcT4gPC94bXBNTTpIaXN0b3J5PiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/Ph33cm0AAAO8SURBVDjLhZRdiJRVHMZ/553ZxZ3VtFK60SAW1NmPmXX3YkOjLWzWNhW9qQuRSiGL1CCiIsOLIkq0qNw1hEW8SUwv/IDSdCmIUsjPVCo1pWz2Q9Kd3XZmnY/3PefpYnZnxr58OA/8zzkPz/mfl+c9SGKCu49ehllboOFDGlbvQVKHWudtFPQIetTavFHSosZn90LTVnhwP/ve3408EEWGqYAmVo2Z72FeA5YgFyoLALDG8DnGbEYcl7gNXuUkmwvgxkg3k8wxD28ZEJrwUdkxZIy3jCp7jNTN7mzN1H83FLAkMfvw4udb13JhkEy2UNooGY53M5bJwpURln7w5NpFk28cwlVec/Fj6KE27Pr13RrHho++sdM6d7icldTSLAuyILU0K2elaWuOuDd7//DV9bYEsqtWd2nLe+jjzXDuqRfof/HlJoGCe6dLZ09bSbrY/6cd9iUXj5UMXTyuVCBdPvVjoPa4FQSFPXudJA1IsXMS1G04Sdsnvx49+VtKbtEjzo9GXf7E91aSAkl+U5N8KHLePPmS1LlQwZy5Nnfzph9IOnU1pbZnPuutW7oDrJRI+06DknITzGRKtR+LlQ1jsdJ6tkI/mHdKS3JSImxamtsnG6gNHIHxIBwG5yAIwBiUTEJtbfGDJ5N48ThUVYG1RQ1wX8jDhAwYrz3snz03k/9DJAKh8Sjm83D+/D8kfjkpM8PiDqhMru6oJuw1x/o8CedEYMcDFQ4Xu/J9TDIJ/ngP1dWorq5oHAqNawLCOLyQB57XR1ZKpApW10ZzSksa/RvHGhs1BkU2Npb3hoZK9TVJqWxOo3IJr2FpT2/Hql29A33DVAPu+nVr5sxxUzraMYAzpvSnOGvxgCmAu3TJmdmzVZN4WANX+uncPtjbsv6nXr4dERelWCBp6NNdLgeB5je4H747EyRvFZSJRjUKGgVlolElMzmd+WXAStLYqZN2ZOrdEujCitVNXz++ArTpLfKb3mFo5cougbT5Db164GoQefqAG8kHutUQ1QhoBIp1IVDk0S73yrtflMI//Nya7ly8ATu/FRxl9m/deiix65qoeV0zl2yXLyldP1cpUAqUrp8rX9Ks5T2Cl7Rw1U71DacPu4o31TOAAYyBfekZT/Ru2L+NByLURKooYHHOlQ91jgKWSdUG6qfz1c7T2/Z/+XOn+a/3sDabhhnT15H3FlgbHHQ465zKhnI4OWudDmJZwD13rauNVN2ew8qJMYARWO+4LMsNXodFbQ7uB7BOv1fBCYx3BExxmNuD/RcidbCGL60y7QAAAABJRU5ErkJggg==",
AUOptions: {Name: "AUOptions",Desc: "Set Notify before download Windows Updates"},
AutoEndTasks: {Name: "Auto End Tasks",Desc: "Close frozen processes to avoid system crash"},
BtnHostsEdit: {Name: "Hosts Edit"},
BtnPackageManager: {Name: "UWP Apps"},
BtnRestartExplorer: {Name: "Restart Explorer"},
BtnStartupManager: {Name: "Startup Manager"},
BtnSys_Close: {Desc: "Text_Close"},
BtnSys_Language: {Desc: "Language"},
BtnSys_LoadOptimizeConfig: {Desc: "Load optimization configurations file"},
BtnSys_Minimize: {Desc: "Minimize"},
BtnSys_ReloadTab: {Desc: "Reload this tab"},
BtnSys_SaveImage: {Desc: "Self-Capture and Save to Image"},
BtnSys_SaveOptimizeConfigAll: {Desc: "Save all optimization configurations to file"},
BtnSys_SaveOptimizeConfigTab: {Desc: "Save this tab only optimization configuration to file"},
BtnSys_Setting: {Desc: "Setting"},
BtnSys_Theme: {Desc: "Theme"},
ClassicContextMenu: {Name: "Classic Context Menu"},
DiagnosticDataOff: {Name: "Diagnostic Data Off"},
DisableAADCloudSearch: {Name: "Turn off Cloud Content Search AAD",Desc: "Turn off Cloud Content Search for Work or School Account"},
DisableAdsOnLockScreen: {Name: "Disable Ads On Lock Screen"},
DisableAeDebug: {Name: "Disable AeDebug",Desc: "Disable the debugger to speed up error processing"},
DisableAnimationEffectMaxMin: {Name: "Disable Animation Effect Max Min",Desc: "Close animation effect when maximizing or minimizing a window to speed up the window response"},
DisableAppendCompletion: {Name: "Disable Append Completion",Desc: "Disable inline Auto-Complete (Append completion or Auto-fill)"},
DisableAutoDefragIdle: {Name: "Disable Auto Defrag Idle",Desc: "Disable auto defrag when idle to increase working life of SSD"},
DisableAutoInstallationApps: {Name: "Disable Auto Installation Apps"},
DisableAutoplay: {Name: "Disable Autoplay",Desc: "Disable the “Autoplay” feature on drives to avoid virus infection"},
DisableAutoSuggest: {Name: "Disable Auto-Suggest",Desc: "Disable Auto-Suggest (Auto-complete drop-down)"},
DisableAutoWindowsUpdates: {Name: "Disable Auto Windows Updates",Desc: "Disable Automatic Updates"},
DisableBackgroundApps: {Name: "Disable Background Apps"},
DisableBootOptimize: {Name: "Disable Boot Optimize",Desc: "Disable defrag system drive on boot to increase working life of SSD"},
DisableCortana: {Name: "Disable Cortana"},
DisableCrashAutoReboot: {Name: "Disable Crash Auto Reboot",Desc: "Disable automatical reboot when system encounters blue screen of death"},
DisableDeviceSearchHistory: {Name: "Turn off Search history locally",Desc: "Turn off Search history locally on this devices"},
DisableDiagTrack: {Name: "Disable DiagTrack",Desc: "DiagTrack - The Connected User Experiences and Telemetry service enables features that support in-application and connected user experiences.`nAdditionally, this service manages the event driven collection and transmission of diagnostic and usage information (used to improve the experience and quality of the Windows Platform) when the diagnostics and usage privacy option settings are enabled under Feedback and Diagnostics."},
DisabledVBSCodeIntegrity: {Name: "Disabled VBS Code Integrity",Desc: "Disable virtualization-based protection of code integrity"},
DisableErrorReporting: {Name: "Disable Error Reporting",Desc: "Disable screen error reporting to improve system performance"},
DisableFrequentFolders: {Name: "Disable FrequentFolders"},
DisableGameBar: {Name: "Disable Game Bar & Game DVR",Desc: "The Game DVR feature allows you to record your gameplay in the background.`nIt is located on the Game Bar – which offers buttons to record gameplay & take screenshots using the Game DVR feature.`nBut it can slow your gaming performance by recording video in the background."},
DisableGoogleUpdateTask: {Name: "Disable GoogleUpdateTask"},
DisableHibernate: {Name: "Disable Hibernate"},
DisableHybridSleep: {Name: "Disable Hybrid Sleep"},
DisableLockScreen: {Name: "Disable Lock Screen"},
DisableLowDiskSpaceChecks: {Name: "Disable Low Disk Space Checks",Desc: "Optimize disk I/O subsystem to improve system performance"},
Disablememorypagination: {Name: "Disable memory pagination",Desc: "Disable memory pagination and reduce disk I/O to improve application performance.`n(Option may be ignored if physical memory is <1 GB)"},
DisableMenuShowDelay: {Name: "Disable Menu Show Delay",Desc: "Optimized response speed of system display"},
DisableMicrosoftEdgeUpdateTask: {Name: "Disable MicrosoftEdgeUpdateTask"},
DisableMSACloudSearch: {Name: "Turn off Cloud Content Search MSA",Desc: "Turn off Cloud Content Search for Microsoft Account"},
DisableMSDefender: {Name: "Disable Microsoft Defender",Desc: "Enable/Disable Microsoft Defender with 1-click.`nIt will automatically restart the computer."},
DisableOfferSuggestions: {Name: "Disable Offer Suggestions"},
DisablePersonalizedAdsStoreApps: {Name: "Disable PersonalizedAds StoreApps"},
DisablePrefetchParameters: {Name: "Disable Prefetch Parameters",Desc: "Disable prefetch parameters to increase SSD working life"},
DisablePrintSpooler: {Name: "Disable Print Spooler"},
DisableRecentFiles: {Name: "Disable RecentFiles"},
DisableRemoteRegAccess: {Name: "Disable Remote Reg Access",Desc: "Disable registry modification from a remote computer"},
DisableScheduledDefrag: {Name: "Disable Scheduled Defrag"},
DisableSettingsAppSuggestions: {Name: "Disable Settings App Suggestions"},
DisableShortcutText: {Name: "Disable Shortcut Text"},
DisableSleep: {Name: "Disable Sleep"},
DisableStartMenuAppSuggestions: {Name: "Disable Start Menu App Suggestions"},
DisableSyncProviderNotifications: {Name: "Disable Sync Provider Notifications"},
DisableSystemRestore: {Name: "Disable System Restore"},
DisableTailoredExperiences: {Name: "Disable Tailored Experiences"},
DisableTipsAndSuggestions: {Name: "Disable Tips And Suggestions"},
DisableTurnOffDisplay: {Name: "Disable Turn Off Display"},
DisableVisualStudioTelemetry: {Name: "Disable VisualStudio Telemetry"},
DisableWCE: {Name: "Disable WCE Improvement",Desc: "Disable Windows Customer Experience Improvement`n`n- Proxy: This task collects and uploads autochk SQM data if opted-in to the Microsoft Customer Experience Improvement Program.`n- Microsoft Compatibility Appraiser: Collects program telemetry information if opted-in to the Microsoft Customer Experience Improvement Program."},
DisableWebSearch: {Name: "Disable Web Search",Desc: "Disable search online and include web results from Bing for only your account when you do a search on the taskbar"},
DisableWebSearchStartMenu: {Name: "Disable WebSearch Start Menu",Desc: "Disables Web Search in Start Menu"},
DisableWindowsFeedback: {Name: "Disable Windows Feedback"},
DisableWindowsSearch: {Name: "Disable Windows Search"},
EnableDarkMode: {Name: "Enable Dark Mode"},
HideMostUsedApps: {Name: "Hide most used apps",Desc: "Turn off `"Show most used apps`" on Start menu"},
HideStartMenuAccountNotifications: {Name: "Hide account-related notifications",Desc: "Turn off `"Show account-related notifications`" on Start menu"},
HideStartMenuRecentlyAdded: {Name: "Hide recently added apps",Desc: "Turn off `"Show recently added apps`" on Start menu"},
HideStartMenuRecentlyOpened: {Name: "Hide recently opened items",Desc: "Turn off `"Show recently opened items in Start, Jump Lists, and File Explorer`" on Start menu"},
HideStartMenuRecommendations: {Name: "Hide recommendations",Desc: "Turn off `"Show recommendations for tips, shortcuts, new apps, and more`" on Start menu"},
HideWindowsSecurityNoncriticalNotifications: {Name: "Hide WS Non-critical Notifications",Desc: "Only show critical notifications from Windows Security.`nIf the Suppress all notifications GP setting has been enabled, this setting will have no effect."},
HideWindowsSecurityNotifications: {Name: "Hide WS Notifications",Desc: "Hide all notifications from Windows Security."},
HostsEdit_BtnImportFromFile: {Name: "Import from files"},
HostsEdit_BtnImportFromLink: {Desc: "Import from link to hosts"},
HostsEdit_BtnReload: {Name: "Reload hosts file"},
HostsEdit_BtnResetDefault: {Name: "Reset Default"},
HostsEdit_BtnSave: {Name: "Text_Save"},
HostsEdit_BtnSaveAs: {Name: "Save As"},
HostsEdit_TxtSelectLink: {Name: "Select link for import block list to hosts:"},
IncreaseIconCache: {Name: "Increase Icon Cache",Desc: "Increase system icon cache and speed up desktop display"},
IoPageLockLimit: {Name: "Io Page Lock Limit",Desc: "Optimize the defauit settings of memory to improve system performance"},
Link_ClearStartMenu: {Name: "Clear StartMenu"},
Link_DeselectAll: {Name: "Text_DeselectAll"},
Link_SelectAll: {Name: "Text_SelectAll"},
LinkResolveIgnoreLinkInfo: {Name: "Link Resolve Ignore LinkInfo",Desc: "Do not track Shell shortcuts during roaming"},
MouseHoverTime: {Name: "Mouse Hover Time",Desc: "Speed up display speed of Taskbar Window Previews"},
NoInternetOpenWith: {Name: "No Internet OpenWith",Desc: "Turn off Internet File Association service"},
NoResolveSearch: {Name: "No Resolve Search",Desc: "Do not use the search-based method when resolving shell shortcuts"},
NumLockonStartup: {Name: "Num Lock on Startup"},
OpenFileExplorerThisPC: {Name: "Open File Explorer ThisPC"},
OptimizeNetworkTransfer: {Name: "Optimize Network Transfer",Desc: "Optimize network settings to improve transfer performance"},
Optimizeprocessorperformance: {Name: "Optimize processor performance",Desc: "Optimize processor performance to make applications, games, etc. run more smoothly."},
OptimizeRefreshPolicy: {Name: "Optimize Refresh Policy",Desc: "Optimize disk I/O subsystem to improve system performance"},
Optional: {Name: "Optional"},
PackageManager_BtnDisable: {Desc: "Enable/Disable for all users"},
PackageManager_DeprovisionPackage: {Name: "Text_DeprovisionPackage",Desc: "Deprovisions an app Package so new users on the device will no longer have the app automatically installed."},
PackageManager_InstalledAllUsers: {Name: "Text_InstalledAllUsers",Desc: "Show list of installed packages by all users."},
PackageManager_Mode: {Desc: "Installed Mode: Show list of installed packages.`nNot Installed Mode: Show list that is on your computer but not installed by the current user."},
Privacy: {Name: "Privacy"},
ShowExtensions: {Name: "Show Extensions"},
ShowHidden: {Name: "Show Hidden"},
ShowHiddenSystem: {Name: "Show Hidden System"},
ShowThisPC: {Name: "Show ThisPC"},
ShutdownAcceleration: {Name: "Shutdown Acceleration",Desc: "Reduce application idleness at shutdown to improve the shutdown process"},
SnippingPrintScreen: {Name: "Snipping PrintScreen"},
System: {Name: "System"},
Text_Architecture: "Architecture",
Text_Cancel: "Cancel",
Text_CheckUpdate: "Check Update",
Text_ClearStartMenu_Confirm: "Are you sure you want to clear the Start menu layout?`n(A backup file `"WinTune_StartMenuLayout_xxxx.json`" will be created)",
Text_ClearStartMenu_Done: "Clear StartMenu Done!",
Text_Close: "Close",
Text_CommandLine: "Command line",
Text_CurrentVersion: "Current version",
Text_Delete: "Delete",
Text_DeprovisionPackage: "Deprovision Package",
Text_DeselectAll: "Deselect All",
Text_Details: "Details",
Text_Disable: "Disable",
Text_Disabled: "Disabled",
Text_DisableMSDefender0: "Enabling Microsoft Defender requires restarting the computer.`nAre you sure you want to perform this?",
Text_DisableMSDefender1: "Disabling Microsoft Defender requires restarting the computer.`nAre you sure you want to perform this?",
Text_DisplayName: "Display name",
Text_EffectivePath: "Effective path",
Text_Enable: "Enable",
Text_Enabled: "Enabled",
Text_FamilyName: "Family name",
Text_FindRegistry: "Find in Registry",
Text_FullName: "Full name",
Text_Homepage: "Homepage",
Text_HR_Optimize: "------- Optimize -------",
Text_HR_Tools: "-------- Tools --------",
Text_Install: "Install",
Text_InstalledAllUsers: "All Users",
Text_InstalledMode: "Installed Mode",
Text_InstalledPath: "Installed path",
Text_Name: "Name",
Text_NewestVersion: "Newest version",
Text_No: "No",
Text_NotInstalledMode: "Not Installed Mode",
Text_NoUpdate: "No update is available. You are using the latest version.",
Text_OK: "OK",
Text_OpenTarget: "Target location",
Text_Properties: "Properties",
Text_PublisherDisplayName: "Publisher",
Text_Save: "Save",
Text_SearchOnline: "Search online",
Text_SelectAll: "Select All",
Text_SignatureKind: "Signature kind",
Text_Status: "Status",
Text_Target: "Target",
Text_Type: "Type",
Text_Uninstall: "Uninstall",
Text_Update: "Update",
Text_Version: "Version",
Text_WaitDlg: "Please wait...",
Text_WhatsNew: "What’s new",
Text_Yes: "Yes",
UninstallOneDrive: {Name: "Uninstall OneDrive"},
UnpinChat: {Name: "Chat"},
UnpinCopilot: {Name: "Copilot"},
UnpinCortana: {Name: "Cortana"},
UnpinEdge: {Name: "Edge"},
UnpinFileExplorer: {Name: "File Explorer"},
UnpinMail: {Name: "Mail"},
UnpinNewsandInterests: {Name: "News and Interests"},
UnpinSearch: {Name: "Search"},
UnpinStore: {Name: "Store"},
UnpinTaskbar: {Name: "Unpin Taskbar"},
UnpinTaskView: {Name: "TaskView"},
UnpinWidgets: {Name: "Widgets"},
VerCtrl: {Desc: "Click to check for update",Desc1: "There's a new version`n(Click to view details)"}
},
tr: {
Name: "Türkçe",
Translator: "mikropsoft",
Flag: "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAFyWlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgOS4xLWMwMDIgNzkuYTZhNjM5NiwgMjAyNC8wMy8xMi0wNzo0ODoyMyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3AvMS4wLyIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0RXZ0PSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VFdmVudCMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIDI1LjkgKFdpbmRvd3MpIiB4bXA6Q3JlYXRlRGF0ZT0iMjAyNC0wNy0yMlQxODowNDo0MCswNzowMCIgeG1wOk1vZGlmeURhdGU9IjIwMjQtMDctMjJUMTg6MTE6MTUrMDc6MDAiIHhtcDpNZXRhZGF0YURhdGU9IjIwMjQtMDctMjJUMTg6MTE6MTUrMDc6MDAiIGRjOmZvcm1hdD0iaW1hZ2UvcG5nIiBwaG90b3Nob3A6Q29sb3JNb2RlPSIzIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOjdlZTVmNWQxLTg0NTUtNjA0Ni1iNWNlLTBkY2ZmMjYyYjY5ZSIgeG1wTU06RG9jdW1lbnRJRD0iYWRvYmU6ZG9jaWQ6cGhvdG9zaG9wOjVkNmFlNTdiLTUzZmMtMDI0MS1iZDZiLTgwNGUxMzRiZjNjMiIgeG1wTU06T3JpZ2luYWxEb2N1bWVudElEPSJ4bXAuZGlkOjQ5ZGQwYTU4LTBiOTMtODU0ZS1iNmM3LTAzNmRjMmM1MzRkZSI+IDx4bXBNTTpIaXN0b3J5PiA8cmRmOlNlcT4gPHJkZjpsaSBzdEV2dDphY3Rpb249ImNyZWF0ZWQiIHN0RXZ0Omluc3RhbmNlSUQ9InhtcC5paWQ6NDlkZDBhNTgtMGI5My04NTRlLWI2YzctMDM2ZGMyYzUzNGRlIiBzdEV2dDp3aGVuPSIyMDI0LTA3LTIyVDE4OjA0OjQwKzA3OjAwIiBzdEV2dDpzb2Z0d2FyZUFnZW50PSJBZG9iZSBQaG90b3Nob3AgMjUuOSAoV2luZG93cykiLz4gPHJkZjpsaSBzdEV2dDphY3Rpb249InNhdmVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjdlZTVmNWQxLTg0NTUtNjA0Ni1iNWNlLTBkY2ZmMjYyYjY5ZSIgc3RFdnQ6d2hlbj0iMjAyNC0wNy0yMlQxODoxMToxNSswNzowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIDI1LjkgKFdpbmRvd3MpIiBzdEV2dDpjaGFuZ2VkPSIvIi8+IDwvcmRmOlNlcT4gPC94bXBNTTpIaXN0b3J5PiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/PuqD7WAAAAO1SURBVDgRhcFfaJV1HMfx9/f3PM/ZnvNnLbPp3GaaM8oQF11UelGQzgWhIdJVBUaEmpfhTd3UZeCdf4Kom4KSglhFqBhCMcmb0G4CjZwd55ya03bO2TnPeX6/Tx1DWhL1epn42+yy+8mL92BqIgIU0lEUHhcM0SFVgVOW62ikNiFJiJstei/8xG0xdzAJomi9LNoLehaIuM0MDK/YvpJ374BOcgfHAk4Bn7j93kUTsmirgiIJJJBAAgUimW3No8KEjwv7nQ8sFKucggHB0SpWjnjHZufFfzEJARKvNbu7hnusd0xydFhz+YNgUC+WDjZdvCvK2xDHqFYnXJoGZ4CBhOtfgpXL4D23SPgkoavRPlSqze42wG4Oria4ZF2jVD7t5CFJCJMXsN5euna8QLLlGaxSIf92guzjz/Bnz2HlMguFyJHWb4y4kJ+JW4WEPOnahzxyRpicxA2vojz+CcnQIO3r12kdeh81ati6h2FmhlCrY2k3iD8JgjFfKO+LWvMb7dJDj24i6BgIsgw1GpR//J6kr4/ml19T37Idw6BcwdIUt2wpYeYqIIhjrKcHfA7mEDbqgg9PCSHAT10iefkl4r4+8mu/Mb/ndWzRYtyaNbjlQyjLULFI8uoObEkf0SMjaG4OYUgCwpMOGJSEJNTOcSNrEZB9d5L81yos6SPkOf73OWx4FcnOV0jfeoP00w/Jq1VCEJKQhIKGYiFuEyCBABEQIIkOIYQQIgBBQhLin1xAF4OEJEIU0f7hNAGI1j+BDQ7gZ2aQc1CpkJ/9mebB96i/+Tb17S9igwMICBJBIkDVJofXbcI4hgRZGzUalE9PUBgYoPn5F9S3PQ84LC1BsYjrX0q4chVDEMdYTw/KczAjyEatet8D5EnXcZl72swIF6dwq1ZSGj9MYeUK2pcv03r3A2jNo1qD/PgJVKtjaQoSHTLDFL6JstbGaG+pgvlwplXo3mnew6K78b+cJ/voMPn1WezexUQjawk358iPn8BPTUMxRRICBAQzCo3atijLZ+xKuZ+Oxl2Vg81ScVfcbqM4glqdMD0N5gADBVz/UiiVwHs6DGhHMWkWDhXna7tNYIG/COP80OojWVLYHHnP/zLDO0dX1jy6YuramMnocAYY4BDdjdqYeR3wQBBIQhKSkIQkJBEArwDiQNpqjjndwJjFmMWxgJwjyf0e1843BPlxL3kv4SW8hJfwklcI40mWbSj4fI93joVi7iAzzIeTmD0H0SimxwIsN26pYpyKvI46Bf7NH+m1EV7ifPXCAAAAAElFTkSuQmCC",
AUOptions: {Name: "AU Seçenekleri",Desc: "Windows Güncellemelerini İndirmeden Önce Bildir"},
AutoEndTasks: {Name: "Görevleri Otomatik Sonlandır",Desc: "Sistemin çökmesini önlemek için donmuş işlemleri kapat"},
BtnHostsEdit: {Name: "Hosts Düzenle"},
BtnPackageManager: {Name: "UWP Uygulamaları"},
BtnRestartExplorer: {Name: "Explorer'ı Yeniden Başlat"},
BtnStartupManager: {Name: "Başlangıç Yöneticisi"},
BtnSys_Close: {Desc: "Kapat"},
BtnSys_Language: {Desc: "Dil"},
BtnSys_LoadOptimizeConfig: {Desc: "Optimizasyon yapılandırma dosyasını yükle"},
BtnSys_Minimize: {Desc: "Simge Durumuna Küçült"},
BtnSys_ReloadTab: {Desc: "Bu sekmeyi yeniden yükle"},
BtnSys_SaveImage: {Desc: "Kendi Ekran Görüntüsünü Al ve Görüntü Olarak Kaydet"},
BtnSys_SaveOptimizeConfigAll: {Desc: "Tüm optimizasyon yapılandırmalarını dosyaya kaydet"},
BtnSys_SaveOptimizeConfigTab: {Desc: "Bu sekme için yalnızca optimizasyon yapılandırmasını dosyaya kaydet"},
BtnSys_Setting: {Desc: "Ayar"},
BtnSys_Theme: {Desc: "Tema"},
ClassicContextMenu: {Name: "Klasik Bağlam Menüsü"},
DiagnosticDataOff: {Name: "Tanılama Verilerini Kapat"},
DisableAADCloudSearch: {Name: "Bulut İçerik Aramasını AAD'den Kapat",Desc: "İş veya Okul Hesabı için Bulut İçerik Aramasını Kapat"},
DisableAdsOnLockScreen: {Name: "Kilitleme Ekranında Reklamları Kapat"},
DisableAeDebug: {Name: "AeDebug'u Devre Dışı Bırak",Desc: "Hata işleme hızını artırmak için hata ayıklayıcıyı devre dışı bırak"},
DisableAnimationEffectMaxMin: {Name: "Maksimum Min Animasyon Efektini Kapat",Desc: "Pencereyi büyütme veya küçültme sırasında animasyon efektini kapat ve pencere yanıt hızını artır"},
DisableAppendCompletion: {Name: "Ek Tamamlamayı Devre Dışı Bırak",Desc: "Satır içi Otomatik Tamamlama (Ek tamamlamayı veya Otomatik doldurma) devre dışı bırak"},
DisableAutoDefragIdle: {Name: "Boşta Otomatik Birleştirmeyi Kapat",Desc: "SSD'nin çalışma ömrünü artırmak için boşta otomatik birleştirmeyi devre dışı bırak"},
DisableAutoInstallationApps: {Name: "Otomatik Uygulama Kurulumunu Kapat"},
DisableAutoplay: {Name: "Otomatik Oynatmayı Kapat",Desc: "Sürücülerdeki “Otomatik Oynat” özelliğini devre dışı bırak ve virüs bulaşmasını önle"},
DisableAutoSuggest: {Name: "Otomatik Öneriyi Devre Dışı Bırak",Desc: "Otomatik Öneriyi (Otomatik tamamlama açılır listesi) devre dışı bırak"},
DisableAutoWindowsUpdates: {Name: "Otomatik Windows Güncellemelerini Kapat",Desc: "Otomatik Güncellemeleri Devre Dışı Bırak"},
DisableBackgroundApps: {Name: "Arka Plan Uygulamalarını Devre Dışı Bırak"},
DisableBootOptimize: {Name: "Önyükleme Optimizasyonunu Kapat",Desc: "Önyükleme sırasında sistem sürücüsünü birleştirmeyi devre dışı bırak ve SSD'nin çalışma ömrünü artır"},
DisableCortana: {Name: "Cortana'yı Devre Dışı Bırak"},
DisableCrashAutoReboot: {Name: "Çökme Sonrası Otomatik Yeniden Başlatmayı Kapat",Desc: "Mavi ekran ölümle karşılaştığında otomatik yeniden başlatmayı devre dışı bırak"},
DisableDeviceSearchHistory: {Name: "Yerel Arama Geçmişini Kapat",Desc: "Bu cihazlarda yerel arama geçmişini kapat"},
DisableDiagTrack: {Name: "DiagTrack'i Devre Dışı Bırak",Desc: "DiagTrack - Bağlı Kullanıcı Deneyimleri ve Telemetri hizmeti, uygulama içi ve bağlı kullanıcı deneyimlerini destekleyen özellikleri etkinleştirir.`nAyrıca, bu hizmet, geri bildirim ve teşhis altındaki teşhis ve kullanım gizlilik seçenek ayarları etkin olduğunda (Windows Platformu deneyimini ve kalitesini iyileştirmek için kullanılan) teşhis ve kullanım bilgilerini toplama ve iletme olaylarını yönetir."},
DisabledVBSCodeIntegrity: {Name: "VBS Kod Bütünlüğünü Devre Dışı Bıraktı",Desc: "Kod bütünlüğünün sanallaştırma tabanlı korunmasını devre dışı bırak"},
DisableErrorReporting: {Name: "Hata Raporlamayı Kapat",Desc: "Ekran hata raporlamasını devre dışı bırak ve sistem performansını artır"},
DisableFrequentFolders: {Name: "Sık Kullanılan Klasörleri Devre Dışı Bırak"},
DisableGameBar: {Name: "Oyun Çubuğunu ve Oyun DVR'ını Kapat",Desc: "Oyun DVR özelliği, oyunlarınızı arka planda kaydetmenize olanak tanır.`nOyun Çubuğu'nda bulunur – Oyun DVR özelliğini kullanarak oyun kaydetme ve ekran görüntüsü alma düğmeleri sunar.`nAncak, arka planda video kaydetmesi nedeniyle oyun performansınızı yavaşlatabilir."},
DisableGoogleUpdateTask: {Name: "Google Güncelleme Görevini Kapat"},
DisableHibernate: {Name: "Hazırda Bekletmeyi Kapat"},
DisableHybridSleep: {Name: "Hibrit Uykuyu Kapat"},
DisableLockScreen: {Name: "Kilitleme Ekranını Kapat"},
DisableLowDiskSpaceChecks: {Name: "Düşük Disk Alanı Kontrollerini Kapat",Desc: "Disk G/Ç alt sistemini optimize edin ve sistem performansını artırın"},
Disablememorypagination: {Name: "Bellek Sayfalama'yı Devre Dışı Bırak",Desc: "Bellek sayfalamasını devre dışı bırak ve disk G/Ç'yi azaltarak uygulama performansını artır.`n(Seçenek, fiziksel bellek <1 GB ise göz ardı edilebilir)"},
DisableMenuShowDelay: {Name: "Menü Gösterim Gecikmesini Kapat",Desc: "Sistem ekran yanıt hızını optimize et"},
DisableMicrosoftEdgeUpdateTask: {Name: "Microsoft Edge Güncelleme Görevini Kapat"},
DisableMSACloudSearch: {Name: "MSA için Bulut İçerik Aramasını Kapat",Desc: "Microsoft Hesabı için Bulut İçerik Aramasını Kapat"},
DisableMSDefender: {Name: "Microsoft Defender'ı Kapat",Desc: "Microsoft Defender'ı tek tıkla etkinleştir/devre dışı bırak.`nBilgisayar otomatik olarak yeniden başlatılacaktır."},
DisableOfferSuggestions: {Name: "Öneri Sunmayı Devre Dışı Bırak"},
DisablePersonalizedAdsStoreApps: {Name: "Kişiselleştirilmiş Reklamları Store Uygulamalarında Kapat"},
DisablePrefetchParameters: {Name: "Ön Bellek Parametrelerini Kapat",Desc: "SSD'nin çalışma ömrünü artırmak için önbellek parametrelerini devre dışı bırak"},
DisablePrintSpooler: {Name: "Yazdırma Biriktiricisini Devre Dışı Bırak"},
DisableRecentFiles: {Name: "Son Dosyaları Devre Dışı Bırak"},
DisableRemoteRegAccess: {Name: "Uzaktan Kayıt Defteri Erişimini Devre Dışı Bırak",Desc: "Uzaktaki bir bilgisayardan kayıt defteri değişikliğini devre dışı bırak"},
DisableScheduledDefrag: {Name: "Planlı Birleştirmeyi Devre Dışı Bırak"},
DisableSettingsAppSuggestions: {Name: "Ayarlar Uygulaması Önerilerini Kapat"},
DisableShortcutText: {Name: "Kısayol Metnini Devre Dışı Bırak"},
DisableSleep: {Name: "Uyku Modunu Kapat"},
DisableStartMenuAppSuggestions: {Name: "Başlat Menüsü Uygulama Önerilerini Kapat"},
DisableSyncProviderNotifications: {Name: "Senkronizasyon Sağlayıcı Bildirimlerini Kapat"},
DisableSystemRestore: {Name: "Sistem Geri Yüklemeyi Kapat"},
DisableTailoredExperiences: {Name: "Özel Deneyimleri Kapat"},
DisableTipsAndSuggestions: {Name: "İpuçları ve Önerileri Kapat"},
DisableTurnOffDisplay: {Name: "Ekranı Kapatmayı Devre Dışı Bırak"},
DisableVisualStudioTelemetry: {Name: "VisualStudio Telemetrisini Kapat"},
DisableWCE: {Name: "WCE İyileştirmesini Devre Dışı Bırak",Desc: "Windows Müşteri Deneyimi İyileştirmesini Devre Dışı Bırak`n`n- Proxy: Bu görev, Microsoft Müşteri Deneyimi İyileştirme Programına katıldıysanız otomatik olarak toplama ve iletme işlevini gerçekleştirir.`n- Microsoft Uyumluluk Değerlendirici: Microsoft Müşteri Deneyimi İyileştirme Programına katıldıysanız program telemetri bilgilerini toplar."},
DisableWebSearch: {Name: "Web Aramasını Kapat",Desc: "Görev çubuğunda bir arama yaptığınızda çevrimiçi aramayı kapatın ve yalnızca hesabınız için Bing'den web sonuçlarını içermesini kapatın"},
DisableWebSearchStartMenu: {Name: "Başlat Menüsünde Web Aramasını Kapat",Desc: "Başlat Menüsünde Web Aramasını Kapatır"},
DisableWindowsFeedback: {Name: "Windows Geri Bildirimini Kapat"},
DisableWindowsSearch: {Name: "Windows Aramasını Devre Dışı Bırak"},
EnableDarkMode: {Name: "Karanlık Modu Etkinleştir"},
HideMostUsedApps: {Name: "En çok kullanılan uygulamaları gizle",Desc: "Başlat menüsünde 'En çok kullanılan uygulamaları göster' seçeneğini kapat"},
HideStartMenuAccountNotifications: {Name: "Hesapla ilgili bildirimleri gizle",Desc: "Başlat menüsünde 'Hesapla ilgili bildirimleri göster' seçeneğini kapat"},
HideStartMenuRecentlyAdded: {Name: "Son eklenen uygulamaları gizle",Desc: "Başlat menüsünde 'Son eklenen uygulamaları göster' seçeneğini kapat"},
HideStartMenuRecentlyOpened: {Name: "Son açılan öğeleri gizle",Desc: "Başlat, Atlama Listeleri ve Dosya Gezgini'nde 'Son açılan öğeleri göster' seçeneğini kapat"},
HideStartMenuRecommendations: {Name: "Önerileri gizle",Desc: "Başlat menüsünde 'İpuçları, kısayollar, yeni uygulamalar ve daha fazlası için önerileri göster' seçeneğini kapat"},
HideWindowsSecurityNoncriticalNotifications: {Name: "Windows Güvenlik Kritik Olmayan Bildirimleri Gizle",Desc: "Windows Güvenliğinden yalnızca kritik bildirimleri göster.`nTüm bildirimleri engelle GP ayarı etkinleştirilmişse, bu ayarın bir etkisi olmayacaktır."},
HideWindowsSecurityNotifications: {Name: "Windows Güvenlik Bildirimlerini Gizle",Desc: "Windows Güvenliğinden gelen tüm bildirimleri gizle."},
HostsEdit_BtnImportFromFile: {Name: "Dosyalardan İçe Aktar"},
HostsEdit_BtnImportFromLink: {Desc: "Bağlantıdan hosts dosyasına içe aktar"},
HostsEdit_BtnReload: {Name: "Hosts dosyasını yeniden yükle"},
HostsEdit_BtnResetDefault: {Name: "Varsayılanı Sıfırla"},
HostsEdit_BtnSave: {Name: "Kaydet"},
HostsEdit_BtnSaveAs: {Name: "Farklı Kaydet"},
HostsEdit_TxtSelectLink: {Name: "İçe aktarma engelleme listesi için bağlantı seçin:"},
IncreaseIconCache: {Name: "Simge Önbelleğini Artır",Desc: "Sistem simge önbelleğini artır ve masaüstü ekranını hızlandır"},
IoPageLockLimit: {Name: "Io Sayfa Kilit Sınırı",Desc: "Sistem performansını artırmak için bellek varsayılan ayarlarını optimize et"},
Link_ClearStartMenu: {Name: "Başlat Menüsünü Temizle"},
Link_DeselectAll: {Name: "Tümünü Seçme"},
Link_SelectAll: {Name: "Tümünü Seç"},
LinkResolveIgnoreLinkInfo: {Name: "Bağlantı Çözümleme Bağlantı Bilgilerini Yoksay",Desc: "Dolaşırken Kabuk kısayollarını izlemeyin"},
MouseHoverTime: {Name: "Fare Üzerine Gelme Süresi",Desc: "Görev Çubuğu Pencere Ön İzlemelerinin gösterim hızını artır"},
NoInternetOpenWith: {Name: "İnternetsiz Aç",Desc: "İnternet Dosya İlişkilendirme hizmetini kapat"},
NoResolveSearch: {Name: "Çözüm Aramasını Yapma",Desc: "Kabuk kısayollarını çözerken arama tabanlı yöntemi kullanmayın"},
NumLockonStartup: {Name: "Başlangıçta Num Lock"},
OpenFileExplorerThisPC: {Name: "Dosya Gezgini Bu Bilgisayarı Aç"},
OptimizeNetworkTransfer: {Name: "Ağ Transferini Optimize Et",Desc: "Ağ ayarlarını optimize ederek transfer performansını iyileştirin"},
Optimizeprocessorperformance: {Name: "İşlemci Performansını Optimize Et",Desc: "Uygulamaların, oyunların vb. daha sorunsuz çalışması için işlemci performansını optimize edin"},
OptimizeRefreshPolicy: {Name: "Yenileme Politikasını Optimize Et",Desc: "Sistem performansını artırmak için disk G/Ç alt sistemini optimize edin"},
Optional: {Name: "Opsiyonel"},
PackageManager_BtnDisable: {Desc: "Tüm kullanıcılar için etkinleştir/devre dışı bırak"},
PackageManager_DeprovisionPackage: {Name: "Uygulama Paketinin Kaldırılması",Desc: "Bir uygulama paketini kaldırır, böylece cihazdaki yeni kullanıcılar artık uygulamanın otomatik olarak kurulmasına sahip olmayacaklar."},
PackageManager_InstalledAllUsers: {Name: "Tüm Kullanıcılar Tarafından Yüklenenler",Desc: "Tüm kullanıcılar tarafından yüklenen paketlerin listesini göster"},
PackageManager_Mode: {Desc: "Yüklü Mod: Yüklü paketlerin listesini göster.`nYüklü Değil Modu: Bilgisayarınızda bulunan ancak geçerli kullanıcı tarafından yüklenmeyen paketlerin listesini göster."},
Privacy: {Name: "Gizlilik"},
ShowExtensions: {Name: "Uzantıları Göster"},
ShowHidden: {Name: "Gizli Dosyaları Göster"},
ShowHiddenSystem: {Name: "Gizli Sistem Dosyalarını Göster"},
ShowThisPC: {Name: "Bu Bilgisayarı Göster"},
ShutdownAcceleration: {Name: "Kapanış Hızlandırma",Desc: "Kapanış sırasında uygulama bekleme süresini azaltarak kapanış sürecini iyileştirin"},
SnippingPrintScreen: {Name: "Ekran Görüntüsü Alma"},
System: {Name: "Sistem"},
Text_Architecture: "Mimari",
Text_Cancel: "İptal",
Text_CheckUpdate: "Güncellemeleri Kontrol Et",
Text_ClearStartMenu_Confirm: "Başlat menüsü düzenini temizlemek istediğinizden emin misiniz?`n(Bir yedek dosya 'WinTune_StartMenuLayout_xxxx.json' oluşturulacak)",
Text_ClearStartMenu_Done: "Başlat Menüsü Temizlendi!",
Text_Close: "Kapat",
Text_CommandLine: "Komut Satırı",
Text_CurrentVersion: "Geçerli Sürüm",
Text_Delete: "Sil",
Text_DeprovisionPackage: "Uygulama Paketini Kaldır",
Text_DeselectAll: "Tüm Seçimleri Kaldır",
Text_Details: "Ayrıntılar",
Text_Disable: "Devre Dışı Bırak",
Text_Disabled: "Devre Dışı",
Text_DisableMSDefender0: "Microsoft Defender'ı etkinleştirmek bilgisayarın yeniden başlatılmasını gerektirir.`nBu işlemi yapmak istediğinizden emin misiniz?",
Text_DisableMSDefender1: "Microsoft Defender'ı devre dışı bırakmak bilgisayarın yeniden başlatılmasını gerektirir.`nBu işlemi yapmak istediğinizden emin misiniz?",
Text_DisplayName: "Görünen Ad",
Text_EffectivePath: "Etkili Yol",
Text_Enable: "Etkinleştir",
Text_Enabled: "Etkin",
Text_FamilyName: "Aile Adı",
Text_FindRegistry: "Kayıt Defterinde Bul",
Text_FullName: "Tam Adı",
Text_Homepage: "Ana Sayfa",
Text_HR_Optimize: "------- Optimize -------",
Text_HR_Tools: "-------- Araçlar --------",
Text_Install: "Yükle",
Text_InstalledAllUsers: "Tüm Kullanıcılar",
Text_InstalledMode: "Yüklü Mod",
Text_InstalledPath: "Yüklü Yol",
Text_Name: "Adı",
Text_NewestVersion: "En Yeni Sürüm",
Text_No: "Hayır",
Text_NotInstalledMode: "Yüklü Değil Modu",
Text_NoUpdate: "Güncelleme yok. En son sürümü kullanıyorsunuz.",
Text_OK: "Tamam",
Text_OpenTarget: "Hedef Konum",
Text_Properties: "Özellikler",
Text_PublisherDisplayName: "Yayıncı",
Text_Save: "Kaydet",
Text_SearchOnline: "Çevrimiçi Ara",
Text_SelectAll: "Tümünü Seç",
Text_SignatureKind: "İmza Türü",
Text_Status: "Durum",
Text_Target: "Hedef",
Text_Type: "Tür",
Text_Uninstall: "Kaldır",
Text_Update: "Güncelle",
Text_Version: "Sürüm",
Text_WaitDlg: "Lütfen bekleyin...",
Text_WhatsNew: "Yenilikler",
Text_Yes: "Evet",
UninstallOneDrive: {Name: "OneDrive'ı Kaldır"},
UnpinChat: {Name: "Sohbet"},
UnpinCopilot: {Name: "Copilot"},
UnpinCortana: {Name: "Cortana"},
UnpinEdge: {Name: "Edge"},
UnpinFileExplorer: {Name: "Dosya Gezgini"},
UnpinMail: {Name: "Posta"},
UnpinNewsandInterests: {Name: "Haberler ve İlgi Alanları"},
UnpinSearch: {Name: "Arama"},
UnpinStore: {Name: "Mağaza"},
UnpinTaskbar: {Name: "Görev Çubuğundan Kaldır"},
UnpinTaskView: {Name: "Görev Görünümü"},
UnpinWidgets: {Name: "Widget'lar"},
VerCtrl: {Desc: "Güncellemeleri kontrol etmek için tıklayın",Desc1: "Yeni bir sürüm var`n(Detaylar için tıklayın)"}
},
zh_cn: {
Name: "中文（简体）",
Translator: "Jvcon",
Flag: "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAHYcAAB2HAGnwnjqAAAE7mlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgOS4xLWMwMDEgNzkuMTQ2Mjg5OSwgMjAyMy8wNi8yNS0yMDowMTo1NSAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3AvMS4wLyIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0RXZ0PSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VFdmVudCMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIDI1LjMgKFdpbmRvd3MpIiB4bXA6Q3JlYXRlRGF0ZT0iMjAyNC0wMS0yNFQyMjoyOTowMiswNzowMCIgeG1wOk1vZGlmeURhdGU9IjIwMjQtMDEtMjVUMTA6NTg6NDgrMDc6MDAiIHhtcDpNZXRhZGF0YURhdGU9IjIwMjQtMDEtMjVUMTA6NTg6NDgrMDc6MDAiIGRjOmZvcm1hdD0iaW1hZ2UvcG5nIiBwaG90b3Nob3A6Q29sb3JNb2RlPSIzIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOmVkNWQ2MjVmLTc1MzEtMWE0Ny1iNWFjLTc4MDVmYjIyYjNlNSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDplZDVkNjI1Zi03NTMxLTFhNDctYjVhYy03ODA1ZmIyMmIzZTUiIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDplZDVkNjI1Zi03NTMxLTFhNDctYjVhYy03ODA1ZmIyMmIzZTUiPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJjcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOmVkNWQ2MjVmLTc1MzEtMWE0Ny1iNWFjLTc4MDVmYjIyYjNlNSIgc3RFdnQ6d2hlbj0iMjAyNC0wMS0yNFQyMjoyOTowMiswNzowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIDI1LjMgKFdpbmRvd3MpIi8+IDwvcmRmOlNlcT4gPC94bXBNTTpIaXN0b3J5PiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/Pl2SEAcAAAOYSURBVDjLhZTNb1VVFMV/+9xz73uvH7YVBYEGUAkRNKmRRIzEMFBLBxpw5syBI5SRJA79A0yYFUmc6H9gSBiAH4kkQqIThZDgxAAWSiGlrbSv771779nLwUOwReJK1mDv7LOyP87eJh5icctz1AMbMHURDkVrUvJ9wDYAxAz4z1ZzNqPCY07s9hi9fuWBRmQdTIIse12WfYr8HYwMIN2JWFOEMSVhp5XC56AL69+HNYac1AzTdZmf9yoekilTApVGc/Iexatt0kLMZByqs+J8isV0SL5GMGqoBSbwQG9g+Ezq2cHsiRJkqGvg4IsZI5/dor6Z0/nueaxwaAiJj7uNxs5hG51CBhjW3fYCmFgphr7oeH6EPwJj0zPUVwuWpzeSbaqwpojjJd4LpJkcrWaE0RqLImU5jU51cnBl4SPDCD1PrJbZRPWMjhQbutiI03p3icZrbVQa8dmSMJooL7eoLjcpXumw8cffibt6pIVISDW9VnakM5BPdJoQennOKq3jFmrGvrzG5quXECLubbN18VeGjs2Rlg2aCRuu8Q7UcxHvgqIjObjoFEPHe9bAZnfvfRvzb30uYk8knvz6Os0DywC0v3qKxU+2Yi0RxmoM8NVAulWQPV0RRhKqDRBYwLHJkJIfUIKwqaa61oDaSHdyBNR3ImkpJ4zVKBnCIINsa9kfihsChCEJww8Eg3FJ1HcDrfcWcYnZF3cz98Yu8olV4kttUifwT0zc02HjT1fI9nSo7/b9D+gaD0IIYNCp5yLzH2xHmSgvNbl7dBwbTJA59e3YL/deYOWbUdJ8hnLdz/Aho6MbCKwQ9WyEwrGGsFFQ16hv95ep9f4ClEbn9AjdY+NkWypsKKF//WuZ3QhyzglwFyqEcuEO7vTtINJfgYEP52keXsS7Rthcoux+HOD9zSc552xm+y6qvPG9LLwZJB6BgCis5agb0ErAmmvj3AyT/xDL3ls2u2UHHuLEamv4t8xrHgd1AhiEwYSSrRUMgWZ7+eWQ0sUQ7/UoltoXi/bKySoLyB3/D6pRo6ImVXroc6e0QN7zk41KF4sUMH9QmXF1fOeZsmgczFLif2FGskCj6p7dcXN+ytTPOvRvBAREs9OesqQTCXDp8UQkdxAnmr3OVNASxiLG4tp7qBDIaz8aqnq/y0+5lFy+XjB50qm8KvcXqT7qIVt7Dx9pvoElv4DZYYiTmPY52nZ/DH9i/BJdZ4O8X9o6/A0kGDN/Gi4umQAAAABJRU5ErkJggg==",
AUOptions: {Name: "AU选项",Desc: "在下载Windows更新前设置通知"},
AutoEndTasks: {Name: "自动结束任务",Desc: "关闭冻结的进程以避免系统崩溃"},
BtnHostsEdit: {Name: "主机编辑"},
BtnRestartExplorer: {Name: "重启资源管理器"},
BtnSys_Close: {Desc: "关闭"},
BtnSys_Language: {Desc: "语言"},
BtnSys_LoadOptimizeConfig: {Desc: "加载优化配置文件"},
BtnSys_Minimize: {Desc: "最小化"},
BtnSys_SaveImage: {Desc: "自我捕捉并保存为图像"},
BtnSys_SaveOptimizeConfigAll: {Desc: "将所有优化配置保存到文件"},
BtnSys_SaveOptimizeConfigTab: {Desc: "仅保存此标签的优化配置到文件"},
BtnSys_Setting: {Desc: "设置"},
BtnSys_Theme: {Desc: "主题"},
ClassicContextMenu: {Name: "经典上下文菜单"},
DiagnosticDataOff: {Name: "诊断数据关闭"},
DisableAdsOnLockScreen: {Name: "禁用锁屏广告"},
DisableAeDebug: {Name: "禁用AeDebug",Desc: "禁用调试器以加快错误处理"},
DisableAnimationEffectMaxMin: {Name: "禁用最大最小动画效果",Desc: "关闭窗口最大化或最小化时的动画效果以加快窗口响应速度"},
DisableAppendCompletion: {Name: "禁用追加完成",Desc: "禁用内联自动完成（追加完成或自动填充）"},
DisableAutoDefragIdle: {Name: "禁用空闲状态下的自动碎片整理",Desc: "闲置时禁用自动碎片整理以延长SSD的使用寿命"},
DisableAutoInstallationApps: {Name: "禁用自动安装应用"},
DisableAutoplay: {Name: "禁用自动播放",Desc: "禁用驱动器上的“自动播放”功能以避免病毒感染"},
DisableAutoSuggest: {Name: "禁用自动建议",Desc: "禁用自动建议（自动完成下拉）"},
DisableAutoWindowsUpdates: {Name: "禁用自动Windows更新",Desc: "禁用自动更新"},
DisableBackgroundApps: {Name: "禁用后台应用"},
DisableBootOptimize: {Name: "禁用启动优化",Desc: "禁用启动时对系统驱动器的碎片整理以延长SSD的使用寿命"},
DisableCortana: {Name: "禁用Cortana"},
DisableCrashAutoReboot: {Name: "禁用崩溃自动重启",Desc: "当系统遇到蓝屏死机时禁用自动重启"},
DisableDiagTrack: {Name: "禁用DiagTrack"},
DisabledVBSCodeIntegrity: {Name: "禁用VBS代码完整性",Desc: "禁用基于虚拟化的代码完整性保护"},
DisableErrorReporting: {Name: "禁用错误报告",Desc: "禁用屏幕错误报告以提高系统性能"},
DisableFrequentFolders: {Name: "禁用常用文件夹"},
DisableGameBar: {Name: "禁用游戏栏和游戏DVR",Desc: "游戏DVR功能允许你在后台记录你的游戏。它位于游戏栏上 - 提供了使用游戏DVR功能记录游戏和截图的按钮。但是，通过在后台录制视频，它可能会降低你的游戏性能。"},
DisableGoogleUpdateTask: {Name: "禁用Google更新任务"},
DisableHibernate: {Name: "禁用休眠"},
DisableHybridSleep: {Name: "禁用混合休眠"},
DisableLockScreen: {Name: "禁用锁屏"},
DisableLowDiskSpaceChecks: {Name: "禁用低磁盘空间检查",Desc: "优化磁盘I/O子系统以提高系统性能"},
Disablememorypagination: {Name: "禁用内存分页",Desc: "禁用内存分页并减少磁盘I/O以提高应用程序性能。`n(如果物理内存<1 GB，此选项可能会被忽略)"},
DisableMenuShowDelay: {Name: "禁用菜单显示延迟",Desc: "优化系统显示的响应速度"},
DisableMicrosoftEdgeUpdateTask: {Name: "禁用Microsoft Edge更新任务"},
DisableOfferSuggestions: {Name: "禁用提供建议"},
DisablePersonalizedAdsStoreApps: {Name: "禁用个性化广告商店应用"},
DisablePrefetchParameters: {Name: "禁用预取参数",Desc: "禁用预取参数以延长SSD的使用寿命"},
DisablePrintSpooler: {Name: "禁用打印服务"},
DisableRecentFiles: {Name: "禁用最近的文件"},
DisableRemoteRegAccess: {Name: "禁用远程注册访问",Desc: "禁止从远程计算机修改注册表"},
DisableScheduledDefrag: {Name: "禁用计划碎片整理"},
DisableSettingsAppSuggestions: {Name: "禁用设置应用建议"},
DisableShortcutText: {Name: "禁用快捷方式文本"},
DisableSleep: {Name: "禁用睡眠"},
DisableSyncProviderNotifications: {Name: "禁用同步提供商通知"},
DisableSystemRestore: {Name: "禁用系统还原"},
DisableTailoredExperiences: {Name: "禁用定制体验"},
DisableTipsAndSuggestions: {Name: "禁用提示和建议"},
DisableTurnOffDisplay: {Name: "禁用关闭显示"},
DisableVisualStudioTelemetry: {Name: "禁用VisualStudio遥测"},
DisableWCE: {Name: "禁用WCE改进",Desc: "禁用Windows客户体验改进`n`n- 代理：此任务收集并上传autochk SQM数据，如果选择加入Microsoft客户体验改进计划。`n- Microsoft兼容性评估器：如果选择加入Microsoft客户体验改进计划，将收集程序遥测信息。"},
DisableWebSearch: {Name: "禁用网络搜索"},
DisableWebSearchStartMenu: {Name: "禁用网络搜索开始菜单",Desc: "禁用开始菜单中的网络搜索"},
DisableWindowsFeedback: {Name: "禁用Windows反馈"},
DisableWindowsSearch: {Name: "禁用Windows搜索"},
EnableDarkMode: {Name: "启用暗黑模式"},
HostsEdit_BtnImportFromFile: {Name: "从文件导入"},
HostsEdit_BtnImportFromLink: {Name: "从链接导入"},
HostsEdit_BtnReload: {Name: "重新加载主机文件"},
HostsEdit_BtnResetDefault: {Name: "重置默认"},
HostsEdit_BtnSave: {Name: "保存"},
HostsEdit_BtnSaveAs: {Name: "另存为"},
IncreaseIconCache: {Name: "增加图标缓存",Desc: "增加系统图标缓存并加快桌面显示速度"},
IoPageLockLimit: {Name: "I/O页面锁定限制",Desc: "优化内存的默认设置以提高系统性能"},
Link_ClearStartMenu: {Name: "清除开始菜单"},
LinkResolveIgnoreLinkInfo: {Name: "链接解析忽略链接信息",Desc: "在漫游时不跟踪Shell快捷方式"},
MouseHoverTime: {Name: "鼠标悬停时间",Desc: "加快任务栏窗口预览的显示速度"},
NoInternetOpenWith: {Name: "无互联网打开方式",Desc: "关闭互联网文件关联服务"},
NoResolveSearch: {Name: "无解析搜索",Desc: "在解析shell快捷方式时不使用基于搜索的方法"},
NumLockonStartup: {Name: "启动时数字锁定"},
OpenFileExplorerThisPC: {Name: "打开文件资源管理器ThisPC"},
OptimizeNetworkTransfer: {Name: "优化网络传输",Desc: "优化网络设置以提高传输性能"},
Optimizeprocessorperformance: {Name: "优化处理器性能",Desc: "优化处理器性能使应用程序、游戏等运行更加流畅。"},
OptimizeRefreshPolicy: {Name: "优化刷新策略",Desc: "优化磁盘I/O子系统以提高系统性能"},
Optional: {Name: "可选"},
Privacy: {Name: "隐私"},
ShowExtensions: {Name: "显示扩展名"},
ShowHidden: {Name: "显示隐藏文件"},
ShowHiddenSystem: {Name: "显示隐藏的系统文件"},
ShowThisPC: {Name: "显示此电脑"},
ShutdownAcceleration: {Name: "关机加速",Desc: "减少关机时的应用程序空闲以改善关机过程"},
SnippingPrintScreen: {Name: "截图打印屏幕"},
System: {Name: "系统"},
Text_DeselectAll: "取消全选",
Text_SelectAll: "全选",
UninstallOneDrive: {Name: "卸载OneDrive"},
UnpinChat: {Name: "取消固定聊天"},
UnpinCopilot: {Name: "取消固定Copilot"},
UnpinCortana: {Name: "取消固定Cortana"},
UnpinEdge: {Name: "取消固定Edge"},
UnpinFileExplorer: {Name: "取消固定文件资源管理器"},
UnpinMail: {Name: "取消固定邮件"},
UnpinNewsandInterests: {Name: "取消固定新闻和兴趣"},
UnpinSearch: {Name: "取消固定搜索"},
UnpinStore: {Name: "取消固定商店"},
UnpinTaskbar: {Name: "取消固定任务栏"},
UnpinTaskView: {Name: "取消固定任务视图"},
UnpinWidgets: {Name: "取消固定小部件"}
}
}